# Generated by Django 3.2.16 on 2023-12-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_congratulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='birthday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congratulations', to='birthday.birthday'),
        ),
    ]
